os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

env:
  - CODE_VERSION="0.10.1"
  - CODE_VERSION="0.10.9"
  - CODE_VERSION="1.0.0"

install:
  - npm install

script:
  - npm test --silent